/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/models/beach/beach.gltf 
Author: N01516 (https://sketchfab.com/N01506)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mystery-shack-cd0cfc4bc60c46ba8c2dc3a8538b94e5
Title: Mystery Shack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/beach.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.45, 3.607, 4.481]}>
        <mesh geometry={nodes.pCylinder57_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.pCylinder57_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <group position={[-2.681, 15.171, -4.126]}>
        <mesh geometry={nodes.pCube140_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.pCube140_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <group position={[4.355, 9.353, -7.301]}>
        <mesh geometry={nodes.pCube170_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.pCube170_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <group position={[6.014, 0, -0.74]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.polySurface5510_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface5511_lambert1_0.geometry} material={materials.lambert1} />
      </group>
      <group position={[0, -0.214, -0.391]} rotation={[0.035, 0, 0]}>
        <mesh geometry={nodes.polySurface6998_red_paint_0.geometry} material={materials.red_paint} />
        <mesh geometry={nodes.polySurface6998_red_paint_dark_0.geometry} material={materials.red_paint_dark} />
      </group>
      <group position={[0, -0.171, -0.218]} rotation={[0.017, 0, 0]}>
        <mesh geometry={nodes.polySurface6997_red_paint_0.geometry} material={materials.red_paint} />
        <mesh geometry={nodes.polySurface6997_red_paint_dark_0.geometry} material={materials.red_paint_dark} />
      </group>
      <group position={[0, -0.025, 0.241]} rotation={[-0.017, 0, 0]}>
        <mesh geometry={nodes.polySurface6996_red_paint_0.geometry} material={materials.red_paint} />
        <mesh geometry={nodes.polySurface6996_red_paint_dark_0.geometry} material={materials.red_paint_dark} />
      </group>
      <group position={[0, 0.837, 1.259]} rotation={[-0.105, 0, 0]}>
        <mesh geometry={nodes.polySurface6995_red_paint_0.geometry} material={materials.red_paint} />
        <mesh geometry={nodes.polySurface6995_red_paint_dark_0.geometry} material={materials.red_paint_dark} />
      </group>
      <mesh geometry={nodes.polySurface7480_lambert1_0.geometry} material={materials.lambert1} position={[0, 0, 0.159]} scale={[1, 1, 1.045]} />
      <group position={[10.676, 4.709, -8.537]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.pCube493_brown_light_3_0.geometry} material={materials.brown_light_3} />
        <mesh geometry={nodes.pCube493_brown_dark_0.geometry} material={materials.brown_dark} />
      </group>
      <group position={[-0.013, 0, 0]}>
        <mesh geometry={nodes.polySurface15898_brick_1_0.geometry} material={materials.brick_1} />
        <mesh geometry={nodes.polySurface15898_brick_2_0.geometry} material={materials.brick_2} />
        <mesh geometry={nodes.polySurface15898_brick_3_0.geometry} material={materials.brick_3} />
      </group>
      <group position={[-2.753, 3.299, -8.584]} scale={0.049}>
        <mesh geometry={nodes.polySurface18532_rubber_black_0.geometry} material={materials.rubber_black} />
        <mesh geometry={nodes.polySurface18532_white_paint_0.geometry} material={materials.white_paint} />
        <mesh geometry={nodes.polySurface18532_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      </group>
      <mesh geometry={nodes.pCube39_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube83_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.pCube90_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface326_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface326_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube92_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.pCube96_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube96_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.pCube129_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface356_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface362_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface362_wood_floor_light_2_0.geometry} material={materials.wood_floor_light_2} />
      <mesh geometry={nodes.polySurface206_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface206_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface421_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface14603_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface14604_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface3390_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface3390_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube195_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.pCube195_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface5482_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface5493_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface5493_wood_floor_light_2_0.geometry} material={materials.wood_floor_light_2} />
      <mesh geometry={nodes.polySurface5508_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface5509_lambert1_0.geometry} material={materials.lambert1} />
      <group position={[-3.716, 12.232, -4.032]}>
        <mesh geometry={nodes.polySurface6555_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.polySurface6555_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <mesh geometry={nodes.polySurface6553_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface6554_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pTorus3_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.pCube303_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube304_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube305_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube306_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube307_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube308_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube309_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube310_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube311_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube312_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube313_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube314_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube315_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube316_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube317_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube318_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube319_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube320_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube321_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube322_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube323_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube324_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube325_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube326_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube327_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube328_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube329_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube330_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube331_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube332_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube333_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube334_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube335_brick_3_0.geometry} material={materials.brick_3} />
      <mesh geometry={nodes.pCube336_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface6904_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.pCylinder76_cooper_0.geometry} material={materials.cooper} />
      <mesh geometry={nodes.polySurface6999_red_paint_0.geometry} material={materials.red_paint} />
      <mesh geometry={nodes.polySurface6999_red_paint_dark_0.geometry} material={materials.red_paint_dark} />
      <mesh geometry={nodes.polySurface6552_yellow_pain_old_0.geometry} material={materials.yellow_pain_old} />
      <mesh geometry={nodes.polySurface6552_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.polySurface15941_metal_dark_0.geometry} material={materials.metal_dark} position={[0, 0, -0.093]} />
      <mesh geometry={nodes.polySurface15942_metal_dark_0.geometry} material={materials.metal_dark} position={[0, 0, -0.093]} />
      <mesh geometry={nodes.polySurface15943_metal_dark_0.geometry} material={materials.metal_dark} position={[0, 0.018, -0.122]} />
      <mesh geometry={nodes.polySurface15944_metal_dark_0.geometry} material={materials.metal_dark} position={[0, 0.105, -0.194]} />
      <mesh geometry={nodes.polySurface15945_metal_dark_0.geometry} material={materials.metal_dark} position={[0, 0.018, -0.147]} />
      <mesh geometry={nodes.polySurface15946_metal_dark_0.geometry} material={materials.metal_dark} position={[0, 0.018, -0.147]} />
      <mesh geometry={nodes.polySurface14044_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface14045_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube381_red_paint_0.geometry} material={materials.red_paint} />
      <mesh geometry={nodes.pCube381_red_paint_dark_0.geometry} material={materials.red_paint_dark} />
      <mesh geometry={nodes.pCube381_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface7492_stone_light_0.geometry} material={materials.stone_light} />
      <group position={[-6.372, 6.095, -4.032]}>
        <mesh geometry={nodes.polySurface9711_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.polySurface9711_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <group position={[-5.094, 9.183, -4.032]}>
        <mesh geometry={nodes.polySurface9712_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.polySurface9712_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <group position={[-7.23, 9.288, -5.932]}>
        <mesh geometry={nodes.polySurface13855_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.polySurface13855_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <mesh geometry={nodes.pCube393_blue_plastic_0.geometry} material={materials.blue_plastic} />
      <mesh geometry={nodes.pPlane12_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.pPlane13_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.polySurface16146_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16147_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16148_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16149_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16150_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16151_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16152_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16153_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16154_lamp_orange_0.geometry} material={materials.lamp_orange} />
      <mesh geometry={nodes.polySurface16154_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16154_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.polySurface16155_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16156_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube395_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube395_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.pCube395_lamp_orange_0.geometry} material={materials.lamp_orange} />
      <mesh geometry={nodes.pCube396_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pCube396_lamp_orange_0.geometry} material={materials.lamp_orange} />
      <mesh geometry={nodes.pCube396_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.polySurface10098_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15934_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15935_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15936_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15937_brown_dark_0.geometry} material={materials.brown_dark} />
      <group position={[10.68, 3.009, -9.447]}>
        <mesh geometry={nodes.polySurface15445_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.polySurface15445_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <group position={[10.68, 2.992, -5.303]}>
        <mesh geometry={nodes.polySurface15447_brown_dark_0.geometry} material={materials.brown_dark} />
        <mesh geometry={nodes.polySurface15447_brown_light_3_0.geometry} material={materials.brown_light_3} />
      </group>
      <mesh geometry={nodes.polySurface15444_brown_light_3_0.geometry} material={materials.brown_light_3} position={[10.676, 4.442, -5.877]} />
      <mesh geometry={nodes.pCylinder85_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.pCylinder85_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface13841_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface13858_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface13997_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface13997_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16241_brown_light_4_0.geometry} material={materials.brown_light_4} />
      <mesh geometry={nodes.polySurface16242_wood_floor_light_1_0.geometry} material={materials.wood_floor_light_1} />
      <mesh geometry={nodes.polySurface16243_brown_light_2_0.geometry} material={materials.brown_light_2} />
      <mesh geometry={nodes.polySurface16244_wood_floor_light_1_0.geometry} material={materials.wood_floor_light_1} />
      <mesh geometry={nodes.polySurface16245_brown_light_4_0.geometry} material={materials.brown_light_4} />
      <mesh geometry={nodes.polySurface16246_wood_floor_light_1_0.geometry} material={materials.wood_floor_light_1} />
      <mesh geometry={nodes.polySurface16247_brown_light_2_0.geometry} material={materials.brown_light_2} />
      <mesh geometry={nodes.polySurface16248_wood_floor_light_1_0.geometry} material={materials.wood_floor_light_1} />
      <mesh geometry={nodes.polySurface16249_brown_light_4_0.geometry} material={materials.brown_light_4} />
      <mesh geometry={nodes.polySurface16250_wood_floor_light_1_0.geometry} material={materials.wood_floor_light_1} />
      <mesh geometry={nodes.pDisc1_grass_1_0.geometry} material={materials.grass_1} />
      <mesh geometry={nodes.pDisc1_grass_2_0.geometry} material={materials.grass_2} />
      <mesh geometry={nodes.polySurface14736_stone_light_0.geometry} material={materials.stone_light} />
      <mesh geometry={nodes.pCube491_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface15351_yellow_pain_old_0.geometry} material={materials.yellow_pain_old} />
      <mesh geometry={nodes.polySurface15351_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.polySurface15442_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15456_red_paint_0.geometry} material={materials.red_paint} />
      <mesh geometry={nodes.polySurface15456_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface15456_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15472_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15472_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15481_red_paint_0.geometry} material={materials.red_paint} />
      <mesh geometry={nodes.polySurface15481_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.polySurface15481_rubber_black_0.geometry} material={materials.rubber_black} />
      <mesh geometry={nodes.polySurface15500_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15500_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15504_orange_coach_01_0.geometry} material={materials.orange_coach_01} />
      <mesh geometry={nodes.polySurface15504_orange_coach_2_0.geometry} material={materials.orange_coach_2} />
      <mesh geometry={nodes.polySurface15526_lamp_white_0.geometry} material={materials.lamp_white} />
      <mesh geometry={nodes.polySurface15526_rubber_black_0.geometry} material={materials.rubber_black} />
      <mesh geometry={nodes.polySurface15526_cooper_0.geometry} material={materials.cooper} />
      <mesh geometry={nodes.polySurface15527_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15527_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface15546_red_paint_0.geometry} material={materials.red_paint} />
      <mesh geometry={nodes.polySurface15546_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15546_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15550_cooper_0.geometry} material={materials.cooper} />
      <mesh geometry={nodes.polySurface15550_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15550_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface15550_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15625_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15625_rubber_black_0.geometry} material={materials.rubber_black} />
      <mesh geometry={nodes.polySurface15625_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface15625_red_paint_0.geometry} material={materials.red_paint} />
      <mesh geometry={nodes.polySurface15625_red_paint_dark_0.geometry} material={materials.red_paint_dark} />
      <mesh geometry={nodes.polySurface15625_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15625_yellow_pain_old_0.geometry} material={materials.yellow_pain_old} />
      <mesh geometry={nodes.polySurface15625_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.polySurface15625_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface15625_lamp_orange_0.geometry} material={materials.lamp_orange} />
      <mesh geometry={nodes.polySurface15625_lamp_white_0.geometry} material={materials.lamp_white} />
      <mesh geometry={nodes.polySurface15625_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15640_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15640_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15640_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15643_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface15643_lamp_orange_0.geometry} material={materials.lamp_orange} />
      <mesh geometry={nodes.polySurface15643_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.polySurface15643_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface15645_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15645_yellow_pain_old_0.geometry} material={materials.yellow_pain_old} />
      <mesh geometry={nodes.polySurface15645_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.polySurface15649_yellow_pain_old_0.geometry} material={materials.yellow_pain_old} />
      <mesh geometry={nodes.polySurface15649_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.polySurface15649_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15660_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15660_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15680_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15680_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15684_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15684_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface15684_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15690_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15690_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15692_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15692_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface15701_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15702_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15704_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15704_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15704_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface15704_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.polySurface15764_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15764_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15764_stone_light_0.geometry} material={materials.stone_light} />
      <mesh geometry={nodes.polySurface15764_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface15764_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15764_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface15764_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.polySurface15780_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface15780_lamp_white_0.geometry} material={materials.lamp_white} />
      <mesh geometry={nodes.polySurface15780_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15783_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15783_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15783_blue_plastic_0.geometry} material={materials.blue_plastic} />
      <mesh geometry={nodes.polySurface15785_blue_plastic_0.geometry} material={materials.blue_plastic} />
      <mesh geometry={nodes.polySurface15785_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15785_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15793_white_paint_0.geometry} material={materials.white_paint} />
      <mesh geometry={nodes.polySurface15793_red_paint_0.geometry} material={materials.red_paint} />
      <mesh geometry={nodes.polySurface15793_red_paint_dark_0.geometry} material={materials.red_paint_dark} />
      <mesh geometry={nodes.polySurface15793_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15965_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface15965_lamp_red_0.geometry} material={materials.lamp_red} />
      <mesh geometry={nodes.polySurface15965_lamp_purple_0.geometry} material={materials.lamp_purple} />
      <mesh geometry={nodes.polySurface15965_lamp_white_0.geometry} material={materials.lamp_white} />
      <mesh geometry={nodes.polySurface15965_lambert1_0.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.polySurface15965_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.polySurface15970_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface15970_red_paint_0.geometry} material={materials.red_paint} />
      <mesh geometry={nodes.pCube494_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.pCube494_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16047_wood_floor_light_2_0.geometry} material={materials.wood_floor_light_2} />
      <mesh geometry={nodes.polySurface16047_wood_floor_light_1_0.geometry} material={materials.wood_floor_light_1} />
      <mesh geometry={nodes.polySurface16047_brown_light_2_0.geometry} material={materials.brown_light_2} />
      <mesh geometry={nodes.polySurface16047_brown_light_4_0.geometry} material={materials.brown_light_4} />
      <mesh geometry={nodes.polySurface16063_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16063_lamp_pink_0.geometry} material={materials.lamp_pink} />
      <mesh geometry={nodes.polySurface16063_lamp_red_0.geometry} material={materials.lamp_red} />
      <mesh geometry={nodes.polySurface16084_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface16084_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16084_metal_dark_0.geometry} material={materials.metal_dark} />
      <mesh geometry={nodes.polySurface16104_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.polySurface16104_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.pCube495_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.pCube495_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.pCube495_wood_floor_light_2_0.geometry} material={materials.wood_floor_light_2} />
      <mesh geometry={nodes.polySurface16139_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16139_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface16139_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.polySurface16139_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface16145_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.polySurface16145_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.polySurface16145_metal_light_0.geometry} material={materials.metal_light} />
      <mesh geometry={nodes.polySurface16145_lamp_yellow_0.geometry} material={materials.lamp_yellow} />
      <mesh geometry={nodes.polySurface16170_wood_floor_light_1_0.geometry} material={materials.wood_floor_light_1} />
      <mesh geometry={nodes.polySurface16170_wood_floor_light_2_0.geometry} material={materials.wood_floor_light_2} />
      <mesh geometry={nodes.polySurface16170_brown_light_2_0.geometry} material={materials.brown_light_2} />
      <mesh geometry={nodes.polySurface16170_brown_light_4_0.geometry} material={materials.brown_light_4} />
      <mesh geometry={nodes.polySurface16383_wood_floor_light_2_0.geometry} material={materials.wood_floor_light_2} />
      <mesh geometry={nodes.polySurface16383_brown_light_2_0.geometry} material={materials.brown_light_2} />
      <mesh geometry={nodes.polySurface16383_brown_light_1_0.geometry} material={materials.brown_light_1} />
      <mesh geometry={nodes.pasted__polySurface411_brown_dark_0.geometry} material={materials.brown_dark} />
      <mesh geometry={nodes.pasted__polySurface411_yellow_paint_0.geometry} material={materials.yellow_paint} />
      <mesh geometry={nodes.pasted__polySurface411_brown_light_3_0.geometry} material={materials.brown_light_3} />
      <mesh geometry={nodes.typeMesh2_metal_dark_0.geometry} material={materials.metal_dark} position={[-1.686, 14.316, -6.652]} rotation={[0.157, Math.PI / 2, 0]} scale={0.214} />
      <mesh geometry={nodes.pCube504_lamp_white_0.geometry} material={materials.lamp_white} position={[-2.569, 3.679, -3.669]} scale={[7.951, 3.952, 14.671]} />
      <mesh geometry={nodes.polySurface18568_roof_3_0.geometry} material={materials.roof_3} />
      <mesh geometry={nodes.polySurface18568_roof_1_0.geometry} material={materials.roof_1} />
      <mesh geometry={nodes.polySurface18568_roof_4_0.geometry} material={materials.roof_4} />
      <mesh geometry={nodes.polySurface18568_roof_2_0.geometry} material={materials.roof_2} />
    </group>
  )
}

useGLTF.preload('/beach.gltf')
